framework:
    # esi:              ~
    secret:             {{ secret }}
    charset:            UTF-8
    router:             { resource: "%kernel.root_dir%/config/routing.yml" }
    form:               true
    csrf_protection:    true
    validation:         { enabled: true, enable_annotations: true }
    templating:         { engines: ['{{ template_engine }}'] } #assets_version: SomeVersionScheme
    session:
        default_locale: en
        lifetime:       3600
        auto_start:     {{ session_start }}
        name:           {{ session_name }}
{{ twig }}
{{ assetic }}
{{ doctrine }}
{{ doctrine_mongodb }}
{{ propel }}
{{ swiftmailer }}
{{ custom }}
{{ mandango_config }}